MySQLDatabase:
  host: '172.17.0.1'
  port: '3306'
  database: 'CloneWarsBase'
  username: 'username'
  password: 'password'
chatShortcuts:
  ooc: ''
  staff: ''
  officer: ''
  server: ''
  batt: ''
  broadcast: ''
  local: ''
