name: CloneWarsBase
version: ${project.version}
main: me.prosl3nderman.clonewarsbase.CloneWarsBase
api-version: 1.16
authors: [ ProSl3nderMan ]
depend: [LuckPerms]
commands:
  CWB:
    description: CWB Admin command for testing and administrating purposes.
