name: CloneWarsBase
version: ${project.version}
main: me.prosl3nderman.clonewarsbase.CloneWarsBase
api-version: 1.16
authors: [ ProSl3nderMan ]
depend: [LuckPerms,TAB]
commands:
  CWB:
    description: CWB Admin command for testing and administrating purposes.
  batt:
    description: Battalion command.
    aliases: [battalion]
